import java.util.Scanner;
import java.util.Random;

public class GuessTheNumber {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        Random random = new Random();
        int rounds = 3;
         // Number of rounds
        int totalScore = 0;

        System.out.println("Welcome to the Guess the Number Game!");
        System.out.println("Rules:");
        System.out.println("1. Guess the number generated by the system.");
        System.out.println("2. You will have limited attempts.");
        System.out.println("3. Points are awarded based on attempts left.");
        System.out.println("Let's begin!\n");

        for (int round = 1; round <= rounds; round++) {
            System.out.println("Round " + round + " of " + rounds);
            int randomNumber = random.nextInt(100) + 1; 
            int attempts = 5; 
            int score = 0;
            boolean guessedCorrectly = false;

            System.out.println("Guess the number between 1 and 100:");
            for (int attempt = 1; attempt <= attempts; attempt++) {
                System.out.print("Attempt " + attempt + ": ");
                int userGuess = scanner.nextInt();

                if (userGuess == randomNumber) {
                    System.out.println("Congratulations! You guessed the correct number.");
                    guessedCorrectly = true;
                    score = (attempts - attempt + 1) * 10; 
                    totalScore += score;
                    System.out.println("You earned " + score + " points this round.");
                    break;
                } else if (userGuess < randomNumber) {
                    System.out.println("Too low! Try again.");
                } else {
                    System.out.println("Too high! Try again.");
                }
            }

            if (!guessedCorrectly) {
                System.out.println("Sorry! You've used all your attempts. The correct number was: " + randomNumber);
            }
            System.out.println();
        }

        System.out.println("Game Over!");
        System.out.println("Your total score: " + totalScore);
        System.out.println("Thanks for playing!");
        scanner.close();
    }
}
